tunnel: 8b55dac2-3d47-41cd-874d-1e9a3593dc11
credentials-file: C:\Users\ZhuanZ\.cloudflared\8b55dac2-3d47-41cd-874d-1e9a3593dc11.json

ingress:
  - hostname: prenceyours.xyz
    service: http://localhost:5000
  - service: http_status:404
